language: generic

sudo: required

services:
  - docker

branches:
  only:
    - main

before_install:
  - docker build -t vltndus95/dimelo-backend -f Dockerfile.dev .

script:
  - docker run -e CI=true vltndus95/dimelo-backend npm run test

after_success:
  - docker build -t vltndus95/docker-backend .

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push vltndus95/dimelo-backend

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-2'
  app: 'dimelo'
  env: 'Dimelo-env'
  bucket_name: $ELASTICBEANSTALK_BUCKET
  bucket_path: 'dimelo'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
