FROM node:12-alpine3.11 As development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --global pm2
RUN apk add --no-cache --virtual .gyp python make g++ pkgconfig pixman-dev cairo-dev pango-dev
RUN npm install

COPY . .

CMD ["npm", "run", "start:dev"]