FROM node:12-alpine3.11

WORKDIR /usr/src/app

COPY package*.json ./

RUN apk add --no-cache --virtual .gyp python make g++ pkgconfig pixman-dev cairo-dev pango-dev
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]
